language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
node_js:
  - "5"
before_script:
  - npm prune
after_success:
  # - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run build && npm run deploy'
